ecommerce_ecommerce:
    resource: "@EcommerceEcommerceBundle/Resources/config/routing.yml"
    prefix:   /ecommerce/

choosit_utilisateurs:
    resource: "@ChoositUtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

choosit_platform:
    resource: "@ChoositPlatformBundle/Resources/config/routing.yml"
    prefix:   /choosit/

