<?php

namespace Choosit\PlatformBundle\Repository;

/**
 * Advert2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Advert2Repository extends \Doctrine\ORM\EntityRepository
{

    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                    ->Select('u')
                    ->Where('u.id IN (:array)')
                    ->setParameter('array', $array);

        return $qb->getQuery()->getResult();

    }
}
